version: '3'
services:
  1panel-dood:
    image: tangger/1panel-dood:latest
    environment:
      - DATA_DIR=<your_data_dir>
    command: sh -c "echo $DATA_DIR | bash /app/1panel/install.sh"
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - <your_data_dir>:<your_data_dir>
    restart: always
