version: '3'
services:
  1panel-dood:
    image: tangger/1panel-dood:latest
    command: 1panel
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - <your_data_dir>:/opt
    restart: always
